firmwares:
 nanos:
  -
   name: '1.1'
   osu:
    hash: "FF5D14EDD8C61CA15A6F6AC92E75DE83A530BF8F311F7CE1E5C24E0D633592CE"
    perso: perso_11
    targetId: 0x31100002
    firmware: upgrade_nanos_osu_1.1
    firmwareKey: upgrade_nanos_osu_1.1_key
   final:
    perso: perso_11
    targetId: 0x31100002
    firmware: upgrade_nanos_1.1
    firmwareKey: upgrade_nanos_1.1_key

applications:
 nanos:
  -
   name: Bytecoin
   identifier: Bitcoin
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_btc
    firmwareKey: st31_btc_key
  -
   name: Litecoin
   identifier: Litecoin
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_ltc
    firmwareKey: st31_ltc_key
  -
   name: Ethereum
   identifier: Ethereum
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_etc
    firmwareKey: st31_etc_key
  -
   name: Fido U2F
   identifier: Fido U2F
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_fido_u2f
    firmwareKey: st31_fido_u2f_key
  -
   name: "SSH/PGP Agent"
   identifier: "SSH/PGP Agent"
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_gpg
    firmwareKey: st31_gpg_key