firmwares:
 nanos:
  -
   name: '1.1'
   osu:
    hash: "FF5D14EDD8C61CA15A6F6AC92E75DE83A530BF8F311F7CE1E5C24E0D633592CE"
    perso: perso_11
    targetId: 0x31100002
    firmware: upgrade_nanos_osu_1.1
    firmwareKey: upgrade_nanos_osu_1.1_key
   final:
    perso: perso_11
    targetId: 0x31100002
    firmware: upgrade_nanos_1.1
    firmwareKey: upgrade_nanos_1.1_key

applications:
 nanos:
  -
   name: Bitcoin
   app_name: Bitcoin
   icon: bitcoin
   version: "1.0"
   notes: "bitcoin_1_0.md"
   hash: FF5D14EDD8C61CA15A6F6AC92E75DE83A530BF8F311F7CE1E5C24E0D633592CE
   bolos_versions:
    min: '1.1'
    max: '1.1'
   permissions:
    - ""
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_btc
    firmwareKey: st31_btc_key
  -
   name: Bitcoin
   app_name: Bitcoin
   icon: bitcoin
   version: "1.1"
   developer: true
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_btc
    firmwareKey: st31_btc_key
  -
   name: Litecoin
   app_name: Litecoin
   icon: litecoin
   version: "1.0"
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_ltc
    firmwareKey: st31_ltc_key
  -
   name: Ethereum
   app_name: Ethereum
   icon: ethereum
   version: "1.0"
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_etc
    firmwareKey: st31_etc_key
  -
   name: Fido U2F
   app_name: Fido U2F
   icon: fido
   version: "1.0"
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_fido_u2f
    firmwareKey: st31_fido_u2f_key
  -
   name: "SSH/PGP Agent"
   app_name: "SSH/PGP Agent"
   version: "1.0"
   icon: ssh
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_gpg
    firmwareKey: st31_gpg_key