firmwares:
 nanos:
# Firmwares for BOLOS >= 1.2
  -
   name: '1.2'
   notes: 'firm_1_2.md'
   bolos_version:
    min: '1.2'
   osu:
    hash: "EE7BAC180DC466E29EBFD98E6AA59E4E62E43046834559762CAC6BACCC41F4F6"
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/upgrade_nanos_osu_1.2
    firmwareKey: nanos_12/upgrade_nanos_osu_1.2_key
   final:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/upgrade_nanos_1.2
    firmwareKey: nanos_12/upgrade_nanos_1.2_key
# Firmwares for BOLOS < 1.2
  -
   name: '1.2'
   notes: 'firm_1_2.md'
   bolos_version:
    max: '1.1'
   osu:
    hash: "EE7BAC180DC466E29EBFD98E6AA59E4E62E43046834559762CAC6BACCC41F4F6"
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/upgrade_nanos_osu_1.2
    firmwareKey: nanos_12/upgrade_nanos_osu_1.2_key
   final:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/upgrade_nanos_1.2
    firmwareKey: nanos_12/upgrade_nanos_1.2_key

applications:
 nanos:
# Applications for BOLOS >= 1.2
  -
   name: Bitcoin
   identifier: Bitcoin
   icon: bitcoin
   version: "1.1.0"
   bolos_version:
    min: '1.2'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/st31_btc
    firmwareKey: nanos_12/st31_btc_key
  -
   name: Ethereum
   identifier: Ethereum
   notes: 'ethereum_1_1.md'
   icon: ethereum
   version: "1.1.0"
   bolos_version:
    min: '1.2'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/st31_etc
    firmwareKey: nanos_12/st31_etc_key
  -
   name: Fido U2F
   identifier: Fido U2F
   icon: fido
   version: "1.1.0"
   bolos_version:
    min: '1.2'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/st31_fido_u2f
    firmwareKey: nanos_12/st31_fido_u2f_key
  -
   name: Litecoin
   identifier: Litecoin
   icon: litecoin
   version: "1.1.0"
   bolos_version:
    min: '1.2'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/st31_ltc
    firmwareKey: nanos_12/st31_ltc_key
  -
   name: "SSH/PGP Agent"
   identifier: "SSH/PGP Agent"
   version: "0.0.1"
   icon: ssh
   developer: true
   bolos_version:
    min: '1.2'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: nanos_12/st31_gpg
    firmwareKey: nanos_12/st31_gpg_key

# Applications for BOLOS < 1.2
  -
   name: Bitcoin
   identifier: Bitcoin
   icon: bitcoin
   version: "1.0.0"
   bolos_version:
    max: '1.1'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_btc
    firmwareKey: st31_btc_key
  -
   name: Ethereum
   identifier: Ethereum
   icon: ethereum
   version: "1.0.0"
   bolos_version:
    max: '1.1'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_etc
    firmwareKey: st31_etc_key
  -
   name: Fido U2F
   identifier: Fido U2F
   icon: fido
   version: "1.0.0"
   bolos_version:
    max: '1.1'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_fido_u2f
    firmwareKey: st31_fido_u2f_key
  -
   name: Litecoin
   identifier: Litecoin
   icon: litecoin
   version: "1.0.0"
   bolos_version:
    min: '1.1'
    max: '1.1'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_ltc
    firmwareKey: st31_ltc_key
  -
   name: "SSH/PGP Agent"
   identifier: "SSH/PGP Agent"
   version: "0.0.1"
   icon: ssh
   developer: true
   bolos_version:
    max: '1.1'
   app:
    perso: perso_11
    targetId: 0x31100002
    firmware: st31_gpg
    firmwareKey: st31_gpg_key
